services:
  - type: web
    name: very-new
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: python app.py
