services:
  - type: web
    name: very-new
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - "**/*"
    aptPackages:
      - chromium
      - chromium-driver
